services:
  pg_database:
    container_name: pg_database
    environment:
      POSTGRES_PASSWORD: 123
      DATABASE_HOST: pg_database
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  server:
    build: .
    container_name: server
    depends_on:
      - pg_database
    ports:
      - 3001:3001
    restart: on-failure
